name: Create PR

on:
  push:
    branches-ignore:
      - develop
      - master
      - production

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  BASE_BRANCH: develop

jobs:

  upsert_pr:
    name: Upsert PR
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lookup PR
        id: lookup
        continue-on-error: true
        run: |
          gh pr view > /dev/null
          if [ $? -eq 0 ]; then
            echo '::set-output name=EXISTS::TRUE'
          else
            echo '::set-output name=EXISTS::FALSE'
          fi

      - name: Debug
        run: echo ${{ steps.lookup.outputs.EXISTS }}

      - name: Determine issue number
        id: number
        run: |
          ISSUE_NUMBER=$(echo ${{ github.ref }} | sed -E 's/^refs\/heads\/(feature|bug|hotfix)\/([0-9]+)-.+$/\2/')
          echo "Issue number: $ISSUE_NUMBER"
          echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"

      - name: Get issue title
        id: title
        env:
          ISSUE_NUMBER: ${{ steps.number.outputs.ISSUE_NUMBER }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"
          TITLE=$(gh issue view "$ISSUE_NUMBER" --json "title" -q ".title")
          echo "Issue title: $TITLE"
          echo "::set-output name=ISSUE_TITLE::$TITLE"

      - name: Create PR
        if: ${{ steps.lookup.outputs.EXISTS == 'FALSE' }}
        env:
          ISSUE_NUMBER: ${{ steps.number.outputs.ISSUE_NUMBER }}
          ISSUE_TITLE: ${{ steps.title.outputs.ISSUE_TITLE }}
        run: |
          gh pr create \
            --base develop \
            --draft \
            --assignee ${{ github.actor }} \
            --title "$ISSUE_TITLE" \
            --body "#$ISSUE_NUMBER $ISSUE_TITLE"
