name: Upsert PR

on:
  push:
    branches-ignore:
      - develop
      - master
      - production

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  BASE_BRANCH: develop

jobs:

  lookup:
    name: Lookup PR
    runs-on: ubuntu-latest
    outputs:
      PR_ID: ${{ steps.pr.outputs.ID }}
    steps:

      - uses: actions/checkout@v2

      - name: Lookup PR
        id: pr
        continue-on-error: true
        run: |
          ID=$(gh pr view --json id --q ".id" || true)
          echo "::set-output name=ID::$ID"

      - name: Debug
        run: echo ${{ steps.pr.outputs.ID }}

  create:
    name: Create PR
    needs:
      - lookup
    if: ${{ needs.lookup.outputs.PR_ID == '' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Determine issue number
        id: number
        run: |
          ISSUE_NUMBER=$(echo ${{ github.ref }} | sed -E 's/^refs\/heads\/(feature|bug|hotfix)\/([0-9]+)-.+$/\2/')
          echo "Issue number: $ISSUE_NUMBER"
          echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"

      - name: Get issue title
        id: title
        env:
          ISSUE_NUMBER: ${{ steps.number.outputs.ISSUE_NUMBER }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"
          TITLE=$(gh issue view "$ISSUE_NUMBER" --json "title" -q ".title")
          echo "Issue title: $TITLE"
          echo "::set-output name=ISSUE_TITLE::$TITLE"

      - name: Get issue body
        id: body
        env:
          ISSUE_NUMBER: ${{ steps.number.outputs.ISSUE_NUMBER }}
        run: |
          BODY=$(gh issue view "$ISSUE_NUMBER" --json "body" -q ".body")
          echo "Issue body: $BODY"
          echo "::set-output name=ISSUE_BODY::$BODY"

      - name: Create PR
        env:
          ISSUE_NUMBER: ${{ steps.number.outputs.ISSUE_NUMBER }}
          ISSUE_TITLE: ${{ steps.title.outputs.ISSUE_TITLE }}
          ISSUE_BODY: ${{ steps.body.outputs.ISSUE_BODY }}
        run: |
          echo -e "$ISSUE_BODY\n\n---\n\n#$ISSUE_NUMBER $ISSUE_TITLE" > ./body

          gh pr create \
            --base develop \
            --draft \
            --assignee ${{ github.actor }} \
            --title "$ISSUE_TITLE" \
            --body-file ./body

  update:
    name: Update PR
    needs:
      - lookup
    if: ${{ needs.lookup.outputs.PR_ID != '' }}
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ needs.lookup.outputs.PR_ID }}
    steps:

      - uses: actions/checkout@v2

      - name: Check commit message
        id: commit
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          echo "Message: $MESSAGE"
          ISSUE_NUMBER=$(echo $MESSAGE | sed -E 's/^.*#([0-9]+).*$/\1/')
          echo "ISSUE from commit: $ISSUE_NUMBER"
          if [[ $ISSUE_NUMBER =~ [^0-9] ]]; then
            echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"
          fi

      - name: Should add issue title
        id: add
        if: ${{ needs.commit.outputs.ISSUE_NUMBER != '' }}
        env:
          PR_BODY: ${{ steps.body.outputs.PR_BODY }}
        run: |
          if [[ ${PR_BODY} != *"#$ISSUE_NUMBER "* ]];then
            echo "::set-output name=ADD_ISSUE::TRUE"
          else
            echo "::set-output name=ADD_ISSUE::FALSE"
          fi

      - name: Get issue title
        id: title
        if: ${{ needs.commit.outputs.ISSUE_NUMBER != '' }}
        env:
          ISSUE_NUMBER: ${{ steps.commit.outputs.ISSUE_NUMBER }}
        run: |
          echo "Issue number: $ISSUE_NUMBER"
          TITLE=$(gh issue view "$ISSUE_NUMBER" --json "title" -q ".title")
          echo "Issue title: $TITLE"
          echo "::set-output name=ISSUE_TITLE::$TITLE"

      - name: Current body
        id: body
        if: ${{ needs.commit.outputs.ISSUE_NUMBER != '' }}
        run: |
          BODY=$(gh pr view --json body -q ".body")
          echo "::set-output name=PR_BODY::$BODY"

      - name: Update PR
        env:
          ISSUE_NUMBER: ${{ steps.commit.outputs.ISSUE_NUMBER }}
          ISSUE_TITLE: ${{ steps.title.outputs.ISSUE_TITLE }}
          PR_BODY: ${{ steps.body.outputs.PR_BODY }}
        run: |
          echo -e "$PR_BODY" > ./body
          echo -e "#$ISSUE_NUMBER $ISSUE_TITLE" >> ./body

          gh pr edit $PR_ID --body-file ./body
