name: Pre-Review Checks

on:
  pull_request:
    types: [ready_for_review]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:

  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: The Check
        run: |
          cat test-file

      - name: Revert PR to Draft
        if: ${{ failure() }}
        run: |
          gh extension install kyanny/gh-pr-draft
          gh pr-draft ${{ github.event.pull_request.number }}
